events {
    worker_connections 1024;
}

http {
    proxy_cache_path /var/cache/nginx levels=1:2 keys_zone=my_cache:10m max_size=1g inactive=60m use_temp_path=off;

    log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                    '$status $body_bytes_sent "$http_referer" '
                    '"$http_user_agent" "$http_x_forwarded_for" '
                    'request_time=$request_time upstream_response_time=$upstream_response_time';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log;

    server {
        listen 8080;
        server_name localhost;
        
        location /stub_status {
            stub_status;
            allow 127.0.0.1;
            allow 172.16.0.0/12; # Docker
            deny all;
        }
    }

    upstream flask_app {
        server app:5000;
    }

    server {
        listen 80;
        server_name localhost;

        # Основные метрики nginx
        location /nginx_status {
            stub_status;
            allow 127.0.0.1;
            allow 172.16.0.0/12;
            deny all;
        }

        location / {
            proxy_pass http://flask_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            proxy_cache my_cache;
            proxy_cache_key "$scheme$request_method$host$request_uri";
            proxy_cache_valid 200 302 5m;
            proxy_cache_valid 404 1m;
            add_header X-Cache-Status $upstream_cache_status;
            
            set $skip_cache 0;
            if ($request_method !~ ^(GET|HEAD)$) {
                set $skip_cache 1;
            }
            
            proxy_no_cache $skip_cache;
            proxy_cache_bypass $skip_cache;
        }

        location /health {
            proxy_pass http://flask_app;
            proxy_cache off;
        }
    }
}